name: Update Age

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Calculate Age and Update README
        run: |
          python3 -c "
          from datetime import date
          import re

          born = date(2010, 1, 31)
          today = date.today()

          age = today.year - born.year - ((today.month, today.day) < (born.month, born.day))

        with open('README.md', 'r') as f:
          content = f.read()

        new_content = re.sub(r'<!--AGE_START-->.*?<!--AGE_END-->', f'<!--AGE_START-->{age}<!--AGE_END-->', content)

        with open ('README.md', 'w') as f:
          f.write(new_content)
        "

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update age based on birthdate"
          file_pattern: README.md
